import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import Navigation from '@/components/Navigation/Navigation';
import './globals.css';

const poppins = Poppins({
	subsets: ['latin'],
	weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
	title: 'Shared Links Custom',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className={poppins.className}>
				<div className='min-h-screen flex'>
					<Navigation />

					<main className='py-5 px-8'>{children}</main>
				</div>
			</body>

			<script
				async
				defer
				crossOrigin='anonymous'
				src='https://connect.facebook.net/en_US/sdk.js'></script>
		</html>
	);
}
