// Generated by https://quicktype.io

export interface PageFields {
	followers_count: number;
	about: string;
	cover: Cover;
	emails: string[];
	fan_count: number;
	link: string;
	name: string;
	picture: Picture;
	id: string;
}

export interface Cover {
	cover_id: string;
	offset_x: number;
	offset_y: number;
	source: string;
	id: string;
}

export interface Picture {
	data: Data;
}

export interface Data {
	height: number;
	is_silhouette: boolean;
	url: string;
	width: number;
}
