// Generated by https://quicktype.io

export interface PageInsights {
	name: string;
	period: string;
	values: Value[];
	title: null | string;
	description: null | string;
	id: string;
}

export interface Value {
	value: number;
	end_time: string;
}

export interface Paging {
	previous: string;
	next: string;
}
